### ISSUE TITLE
Feat: 어제 한 일 페이지 구현

### ISSUE THREAD

**Issue by dogmania** [Kusitms-POPTATO-DEV/Poptato_iOS#29]
## TODO

- [ ] 어제 한 일 조회 API 구현
- [ ] 어제 한 일 조회 페이지 구현
- [ ] 어제 한 일 스낵바 구현
