### ISSUE TITLE
Feat: 카테고리 구현

### ISSUE THREAD

**Issue by dogmania** [Kusitms-POPTATO-DEV/Poptato_iOS#33]
## TODO

- [x] 카테고리 생성 화면 구현
- [x] 이모티콘 조회 API 연결
- [x] 카테고리 생성 API 연결
- [x] 할일 상단 카테고리 리스트 뷰 구현
- [x] 카테고리 조회 API 연결
- [x] 기록 조회 로직 수정
- [x] 카테고리 목록 별 조회 구현
