### ISSUE TITLE
Feat: 카테고리 수정, 삭제 구현

### ISSUE THREAD

**Issue by dogmania** [Kusitms-POPTATO-DEV/Poptato_iOS#37]
## TODO

- [x] 카테고리 수정 API 연결
- [x] 카테고리 삭제 API 연결
- [x] 수정, 삭제 다이얼로그 구현
- [x] 카테고리 생성 화면을 활용하여 수정 로직 구현
