### ISSUE TITLE
Feat: 할 일 바텀시트 카테고리 설정 추가

### ISSUE THREAD

**Issue by dogmania** [Kusitms-POPTATO-DEV/Poptato_iOS#39]
## TODO

- [x] 백로그 할 일 바텀시트 카테고리 설정 추가
- [x] 투데이 할 일 바텀시트 카테고리 설정 추가
- [x] 스플래시 디자인 수정
- [x] 로그인 디자인 수정
- [x] 할일 상세조회 api 연결
